services:
  web:
    build: .
    container_name: django_web_dev
    ports:
      - "8000:8000"
    environment:
      DJANGO_COMMAND: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
