name: Deploy on push to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          clean: false
      
      - name: Merge main into dev
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      
          git fetch origin
      
          git checkout dev || git checkout -b dev origin/dev
          git pull origin dev
      
          git merge origin/main --allow-unrelated-histories --no-edit
          git push origin dev

      - name: Setup askpass and run deploy
        env:
          SUDO_ASKPASS: /tmp/askpass.sh
        run: |
          echo "${{ secrets.SUDO_PASSWORD }}" > /tmp/sudo_pass
          chmod 600 /tmp/sudo_pass

          echo '#!/bin/sh' > /tmp/askpass.sh
          echo 'cat /tmp/sudo_pass' >> /tmp/askpass.sh
          chmod +x /tmp/askpass.sh

          sudo -A ./deploy.sh
