name: deploy on push to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: print whoami and realpath of deploy script
        run: |
          whoami
          pwd
          realpath ./deploy.sh
          ls -l ./deploy.sh

      - name: Run deployment script
        run: sudo ./deploy.sh
