name: Deploy on push to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup askpass and run deploy
        env:
          SUDO_ASKPASS: /tmp/askpass.sh
        run: |
          echo "${{ secrets.SUDO_PASSWORD }}" > /tmp/sudo_pass
          chmod 600 /tmp/sudo_pass

          echo '#!/bin/sh' > /tmp/askpass.sh
          echo 'cat /tmp/sudo_pass' >> /tmp/askpass.sh
          chmod +x /tmp/askpass.sh

          sudo -A ./deploy.sh