name: Deploy on push to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          clean: false
      
      - name: Configure SSH for pushing
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_DEPLOY_KEY }}" > ~/.ssh/runner_deploy_key
          chmod 600 ~/.ssh/runner_deploy_key
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      
          echo "Host github.com
            IdentityFile ~/.ssh/runner_deploy_key
            IdentitiesOnly yes
          " >> ~/.ssh/config

      - name: Merge main into dev
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git remote set-url origin git@github.com:nedasadamavicius/spotify-explorer.git

          git fetch origin

          git checkout dev || git checkout -b dev origin/dev
          git pull origin dev
          git merge origin/main --allow-unrelated-histories --no-edit
          git push origin dev

      - name: Setup askpass and run deploy
        env:
          SUDO_ASKPASS: /tmp/askpass.sh
          SPOTIFY_ENV_PATH: ${{ vars.SPOTIFY_ENV_PATH }}
        run: |
          echo "${{ secrets.SUDO_PASSWORD }}" > /tmp/sudo_pass
          chmod 600 /tmp/sudo_pass

          echo '#!/bin/sh' > /tmp/askpass.sh
          echo 'cat /tmp/sudo_pass' >> /tmp/askpass.sh
          chmod +x /tmp/askpass.sh

          sudo -A ./deploy.sh
